export const placeholderTexts = [
  "Rolling the golf dice...",
  "Asking the senior caddie for advice...",
  "Checking the wind direction...",
  "Calculating optimal trajectory...",
  "Shuffling the golf deck...",
  "Asking the ball what it wants to do...",
  "Checking if the grass is greener on the other side...",
  "Spinning the golf wheel of fortune...",
  "Asking the trees for permission...",
  "Checking if the hole is ready for us...",
  "Flipping a golf coin...",
  "Asking the clouds for guidance...",
  "Checking if the ball is in the mood...",
  "Drawing a golf tarot card...",
  "Asking the sand trap for mercy...",
  "Checking if the flag is waving hello...",
  "Throwing golf dice...",
  "Asking the water hazard to be nice...",
  "Checking if the green is feeling generous...",
  "Consulting the golf course oracle...",
  "Negotiating with the golf course squirrels...",
  "Asking the divot repair tool for wisdom...",
  "Consulting the golf cart GPS...",
  "Checking if the scorecard is feeling lucky...",
  "Asking the golf glove for a good grip...",
  "Consulting the tee box spirits...",
  "Checking if the golf bag is organized...",
  "Asking the range finder for precision...",
  "Consulting the golf course gnomes...",
  "Checking if the golf shoes have good traction...",
  "Asking the golf towel for good luck...",
  "Consulting the golf course weather station...",
  "Checking if the golf ball marker is ready...",
  "Asking the golf umbrella for protection...",
  "Consulting the golf course grounds crew...",
  "Asking the golf course cart path for direction...",
  "Checking if the golf course bunkers are ready...",
  "Calculating distance to the golf course out of bounds stakes...",
  "Checking if the golf course drop zones are marked for this next shot...",
];

export function getRandomPlaceholderText(): string {
  const randomIndex = Math.floor(Math.random() * placeholderTexts.length);
  return placeholderTexts[randomIndex];
}
